### ISSUE TITLE
Audio Ad-Blocking not working as of Soundcloud May 8th Update

### ISSUE THREAD

**Issue by pussinboot** [apsun/SoundCloudAdAway#6]
- Device: E5823 (Sony), Android version 6.0.1 (SDK 23)
- Xposed version ("86"): 
- SoundCloud version ("2017-05-08"): 
- SoundCloud AdAway version ("1.2"): 

Xposed logs below:

```
05-16 09:50:01.907 I/Xposed  (31122): SoundCloudAdAway: SoundCloud AdAway initializing...
05-16 09:50:01.907 I/Xposed  (31122): SoundCloudAdAway: Phone manufacturer: Sony
05-16 09:50:01.907 I/Xposed  (31122): SoundCloudAdAway: Phone model: E5823
05-16 09:50:01.907 I/Xposed  (31122): SoundCloudAdAway: Android version: 6.0.1
05-16 09:50:01.908 I/Xposed  (31122): SoundCloudAdAway: Xposed bridge version: 86
05-16 09:50:02.003 I/Xposed  (31122): SoundCloudAdAway: App version: 2017.05.08-release (655)
05-16 09:50:02.003 I/Xposed  (31122): SoundCloudAdAway: Module version: 1.2 (3)
05-16 09:50:02.004 I/Xposed  (31122): SoundCloudAdAway: Hooking com.soundcloud.android.ads.AdsOperations#insertAudioAd()
05-16 09:50:02.016 E/Xposed  (31122): SoundCloudAdAway: Failed to hook com.soundcloud.android.ads.AdsOperations#insertAudioAd()
05-16 09:50:02.016 E/Xposed  (31122): de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.soundcloud.android.ads.ApiAudioAd
05-16 09:50:02.016 E/Xposed  (31122): 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:64)
05-16 09:50:02.016 E/Xposed  (31122): 	at de.robv.android.xposed.XposedHelpers.getParameterClasses(XposedHelpers.java:503)
05-16 09:50:02.016 E/Xposed  (31122): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:178)
05-16 09:50:02.016 E/Xposed  (31122): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:253)
05-16 09:50:02.016 E/Xposed  (31122): 	at com.crossbowffs.soundcloudadaway.Xutil.findAndHookMethod(Xutil.java:54)
05-16 09:50:02.016 E/Xposed  (31122): 	at com.crossbowffs.soundcloudadaway.Hook.blockPlayQueueAds(Hook.java:34)
05-16 09:50:02.016 E/Xposed  (31122): 	at com.crossbowffs.soundcloudadaway.Hook.handleLoadPackage(Hook.java:140)
05-16 09:50:02.016 E/Xposed  (31122): 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
05-16 09:50:02.016 E/Xposed  (31122): 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
05-16 09:50:02.016 E/Xposed  (31122): 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
05-16 09:50:02.016 E/Xposed  (31122): 	at de.robv.android.xposed.XposedInit$1.beforeHookedMethod(XposedInit.java:93)
05-16 09:50:02.016 E/Xposed  (31122): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:314)
05-16 09:50:02.016 E/Xposed  (31122): 	at android.app.ActivityThread.handleBindApplication(<Xposed>)
05-16 09:50:02.016 E/Xposed  (31122): 	at android.app.ActivityThread.access$1600(ActivityThread.java:154)
05-16 09:50:02.016 E/Xposed  (31122): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1452)
05-16 09:50:02.016 E/Xposed  (31122): 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-16 09:50:02.016 E/Xposed  (31122): 	at android.os.Looper.loop(Looper.java:234)
05-16 09:50:02.016 E/Xposed  (31122): 	at android.app.ActivityThread.main(ActivityThread.java:5526)
05-16 09:50:02.016 E/Xposed  (31122): 	at java.lang.reflect.Method.invoke(Native Method)
05-16 09:50:02.016 E/Xposed  (31122): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
05-16 09:50:02.016 E/Xposed  (31122): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
05-16 09:50:02.016 E/Xposed  (31122): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
05-16 09:50:02.016 E/Xposed  (31122): Caused by: java.lang.ClassNotFoundException: com.soundcloud.android.ads.ApiAudioAd
05-16 09:50:02.016 E/Xposed  (31122): 	at java.lang.Class.classForName(Native Method)
05-16 09:50:02.016 E/Xposed  (31122): 	at java.lang.Class.forName(Class.java:324)
05-16 09:50:02.016 E/Xposed  (31122): 	at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
05-16 09:50:02.016 E/Xposed  (31122): 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:62)
05-16 09:50:02.016 E/Xposed  (31122): 	... 21 more
05-16 09:50:02.016 E/Xposed  (31122): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.soundcloud.android.ads.ApiAudioAd" on path: DexPathList[[zip file "/data/app/com.soundcloud.android-1/base.apk"],nativeLibraryDirectories=[/data/app/com.soundcloud.android-1/lib/arm, /data/app/com.soundcloud.android-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
05-16 09:50:02.016 E/Xposed  (31122): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
05-16 09:50:02.016 E/Xposed  (31122): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
05-16 09:50:02.016 E/Xposed  (31122): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
05-16 09:50:02.016 E/Xposed  (31122): 	... 25 more
05-16 09:50:02.016 E/Xposed  (31122): 	Suppressed: java.lang.ClassNotFoundException: Didn't find class "com.soundcloud.android.ads.ApiAudioAd" on path: DexPathList[[dex file "/data/dalvik-cache/xposed_XResourcesSuperClass.dex"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
05-16 09:50:02.016 E/Xposed  (31122): 		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
05-16 09:50:02.016 E/Xposed  (31122): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
05-16 09:50:02.016 E/Xposed  (31122): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
05-16 09:50:02.016 E/Xposed  (31122): 		... 26 more
05-16 09:50:02.016 E/Xposed  (31122): 		Suppressed: java.lang.ClassNotFoundException: com.soundcloud.android.ads.ApiAudioAd
05-16 09:50:02.016 E/Xposed  (31122): 			at java.lang.Class.classForName(Native Method)
05-16 09:50:02.016 E/Xposed  (31122): 			at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
05-16 09:50:02.016 E/Xposed  (31122): 			at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
05-16 09:50:02.016 E/Xposed  (31122): 			at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
05-16 09:50:02.016 E/Xposed  (31122): 			... 27 more
05-16 09:50:02.016 E/Xposed  (31122): 		Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
05-16 09:50:02.017 I/Xposed  (31122): SoundCloudAdAway: Hooking com.soundcloud.android.ads.AdsOperations#insertVideoAd()
05-16 09:50:02.022 E/Xposed  (31122): SoundCloudAdAway: Failed to hook com.soundcloud.android.ads.AdsOperations#insertVideoAd()
05-16 09:50:02.022 E/Xposed  (31122): de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.soundcloud.android.ads.ApiVideoAd
05-16 09:50:02.022 E/Xposed  (31122): 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:64)
05-16 09:50:02.022 E/Xposed  (31122): 	at de.robv.android.xposed.XposedHelpers.getParameterClasses(XposedHelpers.java:503)
05-16 09:50:02.022 E/Xposed  (31122): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:178)
05-16 09:50:02.022 E/Xposed  (31122): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:253)
05-16 09:50:02.022 E/Xposed  (31122): 	at com.crossbowffs.soundcloudadaway.Xutil.findAndHookMethod(Xutil.java:54)
05-16 09:50:02.022 E/Xposed  (31122): 	at com.crossbowffs.soundcloudadaway.Hook.blockPlayQueueAds(Hook.java:41)
05-16 09:50:02.022 E/Xposed  (31122): 	at com.crossbowffs.soundcloudadaway.Hook.handleLoadPackage(Hook.java:140)
05-16 09:50:02.022 E/Xposed  (31122): 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
05-16 09:50:02.022 E/Xposed  (31122): 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
05-16 09:50:02.022 E/Xposed  (31122): 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
05-16 09:50:02.022 E/Xposed  (31122): 	at de.robv.android.xposed.XposedInit$1.beforeHookedMethod(XposedInit.java:93)
05-16 09:50:02.022 E/Xposed  (31122): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:314)
05-16 09:50:02.022 E/Xposed  (31122): 	at android.app.ActivityThread.handleBindApplication(<Xposed>)
05-16 09:50:02.022 E/Xposed  (31122): 	at android.app.ActivityThread.access$1600(ActivityThread.java:154)
05-16 09:50:02.022 E/Xposed  (31122): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1452)
05-16 09:50:02.022 E/Xposed  (31122): 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-16 09:50:02.022 E/Xposed  (31122): 	at android.os.Looper.loop(Looper.java:234)
05-16 09:50:02.022 E/Xposed  (31122): 	at android.app.ActivityThread.main(ActivityThread.java:5526)
05-16 09:50:02.022 E/Xposed  (31122): 	at java.lang.reflect.Method.invoke(Native Method)
05-16 09:50:02.022 E/Xposed  (31122): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
05-16 09:50:02.022 E/Xposed  (31122): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
05-16 09:50:02.022 E/Xposed  (31122): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
05-16 09:50:02.022 E/Xposed  (31122): Caused by: java.lang.ClassNotFoundException: com.soundcloud.android.ads.ApiVideoAd
05-16 09:50:02.022 E/Xposed  (31122): 	at java.lang.Class.classForName(Native Method)
05-16 09:50:02.022 E/Xposed  (31122): 	at java.lang.Class.forName(Class.java:324)
05-16 09:50:02.022 E/Xposed  (31122): 	at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
05-16 09:50:02.022 E/Xposed  (31122): 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:62)
05-16 09:50:02.022 E/Xposed  (31122): 	... 21 more
05-16 09:50:02.022 E/Xposed  (31122): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.soundcloud.android.ads.ApiVideoAd" on path: DexPathList[[zip file "/data/app/com.soundcloud.android-1/base.apk"],nativeLibraryDirectories=[/data/app/com.soundcloud.android-1/lib/arm, /data/app/com.soundcloud.android-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
05-16 09:50:02.022 E/Xposed  (31122): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
05-16 09:50:02.022 E/Xposed  (31122): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
05-16 09:50:02.022 E/Xposed  (31122): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
05-16 09:50:02.022 E/Xposed  (31122): 	... 25 more
05-16 09:50:02.022 E/Xposed  (31122): 	Suppressed: java.lang.ClassNotFoundException: Didn't find class "com.soundcloud.android.ads.ApiVideoAd" on path: DexPathList[[dex file "/data/dalvik-cache/xposed_XResourcesSuperClass.dex"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
05-16 09:50:02.022 E/Xposed  (31122): 		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
05-16 09:50:02.022 E/Xposed  (31122): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
05-16 09:50:02.022 E/Xposed  (31122): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
05-16 09:50:02.022 E/Xposed  (31122): 		... 26 more
05-16 09:50:02.022 E/Xposed  (31122): 		Suppressed: java.lang.ClassNotFoundException: com.soundcloud.android.ads.ApiVideoAd
05-16 09:50:02.022 E/Xposed  (31122): 			at java.lang.Class.classForName(Native Method)
05-16 09:50:02.022 E/Xposed  (31122): 			at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
05-16 09:50:02.022 E/Xposed  (31122): 			at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
05-16 09:50:02.022 E/Xposed  (31122): 			at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
05-16 09:50:02.022 E/Xposed  (31122): 			... 27 more
05-16 09:50:02.022 E/Xposed  (31122): 		Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
05-16 09:50:02.022 I/Xposed  (31122): SoundCloudAdAway: Hooking com.soundcloud.android.stream.StreamAdapter#addItem()
05-16 09:50:02.034 I/Xposed  (31122): SoundCloudAdAway: Hooking com.soundcloud.android.stream.StreamAdapter#addItem()
05-16 09:50:02.035 I/Xposed  (31122): SoundCloudAdAway: Hooking com.soundcloud.android.ads.AdOverlayController#shouldDisplayAdOverlay()
05-16 09:50:02.037 I/Xposed  (31122): SoundCloudAdAway: Hooking com.soundcloud.android.ads.AdsOperations#applyInterstitialAd()
05-16 09:50:02.042 E/Xposed  (31122): SoundCloudAdAway: Failed to hook com.soundcloud.android.ads.AdsOperations#applyInterstitialAd()
05-16 09:50:02.042 E/Xposed  (31122): de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.soundcloud.android.ads.ApiInterstitial
05-16 09:50:02.042 E/Xposed  (31122): 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:64)
05-16 09:50:02.042 E/Xposed  (31122): 	at de.robv.android.xposed.XposedHelpers.getParameterClasses(XposedHelpers.java:503)
05-16 09:50:02.042 E/Xposed  (31122): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:178)
05-16 09:50:02.042 E/Xposed  (31122): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:253)
05-16 09:50:02.042 E/Xposed  (31122): 	at com.crossbowffs.soundcloudadaway.Xutil.findAndHookMethod(Xutil.java:54)
05-16 09:50:02.042 E/Xposed  (31122): 	at com.crossbowffs.soundcloudadaway.Hook.blockInterstitialAds(Hook.java:88)
05-16 09:50:02.042 E/Xposed  (31122): 	at com.crossbowffs.soundcloudadaway.Hook.handleLoadPackage(Hook.java:143)
05-16 09:50:02.042 E/Xposed  (31122): 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
05-16 09:50:02.042 E/Xposed  (31122): 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
05-16 09:50:02.042 E/Xposed  (31122): 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
05-16 09:50:02.042 E/Xposed  (31122): 	at de.robv.android.xposed.XposedInit$1.beforeHookedMethod(XposedInit.java:93)
05-16 09:50:02.042 E/Xposed  (31122): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:314)
05-16 09:50:02.042 E/Xposed  (31122): 	at android.app.ActivityThread.handleBindApplication(<Xposed>)
05-16 09:50:02.042 E/Xposed  (31122): 	at android.app.ActivityThread.access$1600(ActivityThread.java:154)
05-16 09:50:02.042 E/Xposed  (31122): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1452)
05-16 09:50:02.042 E/Xposed  (31122): 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-16 09:50:02.042 E/Xposed  (31122): 	at android.os.Looper.loop(Looper.java:234)
05-16 09:50:02.042 E/Xposed  (31122): 	at android.app.ActivityThread.main(ActivityThread.java:5526)
05-16 09:50:02.042 E/Xposed  (31122): 	at java.lang.reflect.Method.invoke(Native Method)
05-16 09:50:02.042 E/Xposed  (31122): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
05-16 09:50:02.042 E/Xposed  (31122): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
05-16 09:50:02.042 E/Xposed  (31122): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
05-16 09:50:02.042 E/Xposed  (31122): Caused by: java.lang.ClassNotFoundException: com.soundcloud.android.ads.ApiInterstitial
05-16 09:50:02.042 E/Xposed  (31122): 	at java.lang.Class.classForName(Native Method)
05-16 09:50:02.042 E/Xposed  (31122): 	at java.lang.Class.forName(Class.java:324)
05-16 09:50:02.042 E/Xposed  (31122): 	at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
05-16 09:50:02.042 E/Xposed  (31122): 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:62)
05-16 09:50:02.042 E/Xposed  (31122): 	... 21 more
05-16 09:50:02.042 E/Xposed  (31122): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.soundcloud.android.ads.ApiInterstitial" on path: DexPathList[[zip file "/data/app/com.soundcloud.android-1/base.apk"],nativeLibraryDirectories=[/data/app/com.soundcloud.android-1/lib/arm, /data/app/com.soundcloud.android-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
05-16 09:50:02.042 E/Xposed  (31122): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
05-16 09:50:02.042 E/Xposed  (31122): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
05-16 09:50:02.042 E/Xposed  (31122): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
05-16 09:50:02.042 E/Xposed  (31122): 	... 25 more
05-16 09:50:02.042 E/Xposed  (31122): 	Suppressed: java.lang.ClassNotFoundException: Didn't find class "com.soundcloud.android.ads.ApiInterstitial" on path: DexPathList[[dex file "/data/dalvik-cache/xposed_XResourcesSuperClass.dex"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
05-16 09:50:02.042 E/Xposed  (31122): 		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
05-16 09:50:02.042 E/Xposed  (31122): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
05-16 09:50:02.042 E/Xposed  (31122): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
05-16 09:50:02.042 E/Xposed  (31122): 		... 26 more
05-16 09:50:02.042 E/Xposed  (31122): 		Suppressed: java.lang.ClassNotFoundException: com.soundcloud.android.ads.ApiInterstitial
05-16 09:50:02.042 E/Xposed  (31122): 			at java.lang.Class.classForName(Native Method)
05-16 09:50:02.042 E/Xposed  (31122): 			at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
05-16 09:50:02.042 E/Xposed  (31122): 			at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
05-16 09:50:02.042 E/Xposed  (31122): 			at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
05-16 09:50:02.042 E/Xposed  (31122): 			... 27 more
05-16 09:50:02.042 E/Xposed  (31122): 		Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
05-16 09:50:02.042 I/Xposed  (31122): SoundCloudAdAway: Hooking com.appboy.AppboyGcmReceiver#onReceive()
05-16 09:50:02.043 I/Xposed  (31122): SoundCloudAdAway: Hooking com.soundcloud.android.analytics.appboy.RealAppboyWrapper#registerInAppMessageManager()
05-16 09:50:02.044 I/Xposed  (31122): SoundCloudAdAway: Hooking com.soundcloud.android.analytics.appboy.RealAppboyWrapper#unregisterInAppMessageManager()
05-16 09:50:02.044 I/Xposed  (31122): SoundCloudAdAway: Hooking com.soundcloud.android.configuration.FeatureOperations#isOfflineContentEnabled()
05-16 09:50:02.045 I/Xposed  (31122): SoundCloudAdAway: SoundCloud AdAway initialization complete!
```

**Comment by apsun** [comment]
Thanks, fixed in 0282e80a8a9389ef9a63d3b26c36dc2247265bc5. Will upload new version to Xposed repo shortly.
